<?php

namespace Database\Seeders\Estados;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CidadesParaSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cities')->insert([
        	['city' => 'Abaetetuba', 'state_id' => 14],
            ['city' => 'Abel Figueiredo', 'state_id' => 14],
            ['city' => 'Acará', 'state_id' => 14],
            ['city' => 'Afuá', 'state_id' => 14],
            ['city' => 'Água Azul do Norte', 'state_id' => 14],
            ['city' => 'Alenquer', 'state_id' => 14],
            ['city' => 'Almeirim', 'state_id' => 14],
            ['city' => 'Altamira', 'state_id' => 14],
            ['city' => 'Anajás', 'state_id' => 14],
            ['city' => 'Ananindeua', 'state_id' => 14],
            ['city' => 'Anapu', 'state_id' => 14],
            ['city' => 'Augusto Corrêa', 'state_id' => 14],
            ['city' => 'Aurora do Pará', 'state_id' => 14],
            ['city' => 'Aveiro', 'state_id' => 14],
            ['city' => 'Bagre', 'state_id' => 14],
            ['city' => 'Baião', 'state_id' => 14],
            ['city' => 'Bannach', 'state_id' => 14],
            ['city' => 'Barcarena', 'state_id' => 14],
            ['city' => 'Belém', 'state_id' => 14],
            ['city' => 'Belterra', 'state_id' => 14],
            ['city' => 'Benevides', 'state_id' => 14],
            ['city' => 'Bom Jesus do Tocantins', 'state_id' => 14],
            ['city' => 'Bonito', 'state_id' => 14],
            ['city' => 'Bragança', 'state_id' => 14],
            ['city' => 'Brasil Novo', 'state_id' => 14],
            ['city' => 'Brejo Grande do Araguaia', 'state_id' => 14],
            ['city' => 'Breu Branco', 'state_id' => 14],
            ['city' => 'Breves', 'state_id' => 14],
            ['city' => 'Bujaru', 'state_id' => 14],
            ['city' => 'Cachoeira do Arari', 'state_id' => 14],
            ['city' => 'Cachoeira do Piriá', 'state_id' => 14],
            ['city' => 'Cametá', 'state_id' => 14],
            ['city' => 'Canaã dos Carajás', 'state_id' => 14],
            ['city' => 'Capanema', 'state_id' => 14],
            ['city' => 'Capitão Poço', 'state_id' => 14],
            ['city' => 'Castanhal', 'state_id' => 14],
            ['city' => 'Chaves', 'state_id' => 14],
            ['city' => 'Colares', 'state_id' => 14],
            ['city' => 'Conceição do Araguaia', 'state_id' => 14],
            ['city' => 'Concórdia do Pará', 'state_id' => 14],
            ['city' => 'Cumaru do Norte', 'state_id' => 14],
            ['city' => 'Curionópolis', 'state_id' => 14],
            ['city' => 'Curralinho', 'state_id' => 14],
            ['city' => 'Curuá', 'state_id' => 14],
            ['city' => 'Curuçá', 'state_id' => 14],
            ['city' => 'Dom Eliseu', 'state_id' => 14],
            ['city' => 'Eldorado dos Carajás', 'state_id' => 14],
            ['city' => 'Faro', 'state_id' => 14],
            ['city' => 'Floresta do Araguaia', 'state_id' => 14],
            ['city' => 'Garrafão do Norte', 'state_id' => 14],
            ['city' => 'Goianésia do Pará', 'state_id' => 14],
            ['city' => 'Gurupá', 'state_id' => 14],
            ['city' => 'Igarapé-Açu', 'state_id' => 14],
            ['city' => 'Igarapé-Miri', 'state_id' => 14],
            ['city' => 'Inhangapi', 'state_id' => 14],
            ['city' => 'Ipixuna do Pará', 'state_id' => 14],
            ['city' => 'Irituia', 'state_id' => 14],
            ['city' => 'Itaituba', 'state_id' => 14],
            ['city' => 'Itupiranga', 'state_id' => 14],
            ['city' => 'Jacareacanga', 'state_id' => 14],
            ['city' => 'Jacundá', 'state_id' => 14],
            ['city' => 'Juruti', 'state_id' => 14],
            ['city' => 'Limoeiro do Ajuru', 'state_id' => 14],
            ['city' => 'Mãe do Rio', 'state_id' => 14],
            ['city' => 'Magalhães Barata', 'state_id' => 14],
            ['city' => 'Marabá', 'state_id' => 14],
            ['city' => 'Maracanã', 'state_id' => 14],
            ['city' => 'Marapanim', 'state_id' => 14],
            ['city' => 'Marituba', 'state_id' => 14],
            ['city' => 'Medicilândia', 'state_id' => 14],
            ['city' => 'Melgaço', 'state_id' => 14],
            ['city' => 'Mocajuba', 'state_id' => 14],
            ['city' => 'Moju', 'state_id' => 14],
            ['city' => 'Monte Alegre', 'state_id' => 14],
            ['city' => 'Muaná', 'state_id' => 14],
            ['city' => 'Nova Esperança do Piriá', 'state_id' => 14],
            ['city' => 'Nova Ipixuna', 'state_id' => 14],
            ['city' => 'Nova Timboteua', 'state_id' => 14],
            ['city' => 'Novo Progresso', 'state_id' => 14],
            ['city' => 'Novo Repartimento', 'state_id' => 14],
            ['city' => 'Óbidos', 'state_id' => 14],
            ['city' => 'Oeiras do Pará', 'state_id' => 14],
            ['city' => 'Oriximiná', 'state_id' => 14],
            ['city' => 'Ourém', 'state_id' => 14],
            ['city' => 'Ourilândia do Norte', 'state_id' => 14],
            ['city' => 'Pacajá', 'state_id' => 14],
            ['city' => 'Palestina do Pará', 'state_id' => 14],
            ['city' => 'Paragominas', 'state_id' => 14],
            ['city' => 'Parauapebas', 'state_id' => 14],
            ['city' => 'Pau d`Arco', 'state_id' => 14],
            ['city' => 'Peixe-Boi', 'state_id' => 14],
            ['city' => 'Piçarra', 'state_id' => 14],
            ['city' => 'Placas', 'state_id' => 14],
            ['city' => 'Ponta de Pedras', 'state_id' => 14],
            ['city' => 'Portel', 'state_id' => 14],
            ['city' => 'Porto de Moz', 'state_id' => 14],
            ['city' => 'Prainha', 'state_id' => 14],
            ['city' => 'Primavera', 'state_id' => 14],
            ['city' => 'Quatipuru', 'state_id' => 14],
            ['city' => 'Redenção', 'state_id' => 14],
            ['city' => 'Rio Maria', 'state_id' => 14],
            ['city' => 'Rondon do Pará', 'state_id' => 14],
            ['city' => 'Rurópolis', 'state_id' => 14],
            ['city' => 'Salinópolis', 'state_id' => 14],
            ['city' => 'Salvaterra', 'state_id' => 14],
            ['city' => 'Santa Bárbara do Pará', 'state_id' => 14],
            ['city' => 'Santa Cruz do Arari', 'state_id' => 14],
            ['city' => 'Santa Isabel do Pará', 'state_id' => 14],
            ['city' => 'Santa Luzia do Pará', 'state_id' => 14],
            ['city' => 'Santa Maria das Barreiras', 'state_id' => 14],
            ['city' => 'Santa Maria do Pará', 'state_id' => 14],
            ['city' => 'Santana do Araguaia', 'state_id' => 14],
            ['city' => 'Santarém', 'state_id' => 14],
            ['city' => 'Santarém Novo', 'state_id' => 14],
            ['city' => 'Santo Antônio do Tauá', 'state_id' => 14],
            ['city' => 'São Caetano de Odivelas', 'state_id' => 14],
            ['city' => 'São Domingos do Araguaia', 'state_id' => 14],
            ['city' => 'São Domingos do Capim', 'state_id' => 14],
            ['city' => 'São Félix do Xingu', 'state_id' => 14],
            ['city' => 'São Francisco do Pará', 'state_id' => 14],
            ['city' => 'São Geraldo do Araguaia', 'state_id' => 14],
            ['city' => 'São João da Ponta', 'state_id' => 14],
            ['city' => 'São João de Pirabas', 'state_id' => 14],
            ['city' => 'São João do Araguaia', 'state_id' => 14],
            ['city' => 'São Miguel do Guamá', 'state_id' => 14],
            ['city' => 'São Sebastião da Boa Vista', 'state_id' => 14],
            ['city' => 'Sapucaia', 'state_id' => 14],
            ['city' => 'Senador José Porfírio', 'state_id' => 14],
            ['city' => 'Soure', 'state_id' => 14],
            ['city' => 'Tailândia', 'state_id' => 14],
            ['city' => 'Terra Alta', 'state_id' => 14],
            ['city' => 'Terra Santa', 'state_id' => 14],
            ['city' => 'Tomé-Açu', 'state_id' => 14],
            ['city' => 'Tracuateua', 'state_id' => 14],
            ['city' => 'Trairão', 'state_id' => 14],
            ['city' => 'Tucumã', 'state_id' => 14],
            ['city' => 'Tucuruí', 'state_id' => 14],
            ['city' => 'Ulianópolis', 'state_id' => 14],
            ['city' => 'Uruará', 'state_id' => 14],
            ['city' => 'Vigia', 'state_id' => 14],
            ['city' => 'Viseu', 'state_id' => 14],
            ['city' => 'Vitória do Xingu', 'state_id' => 14],
            ['city' => 'Xinguara', 'state_id' => 14]
        ]);

        $this->command->info('Cidades do Pará importadas com sucesso!');
    }
}
