<?php

namespace Database\Seeders\Estados;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CidadesParaibaSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cities')->insert([
        	['city' => 'Água Branca', 'state_id' => 15],
            ['city' => 'Aguiar', 'state_id' => 15],
            ['city' => 'Alagoa Grande', 'state_id' => 15],
            ['city' => 'Alagoa Nova', 'state_id' => 15],
            ['city' => 'Alagoinha', 'state_id' => 15],
            ['city' => 'Alcantil', 'state_id' => 15],
            ['city' => 'Algodão de Jandaíra', 'state_id' => 15],
            ['city' => 'Alhandra', 'state_id' => 15],
            ['city' => 'Amparo', 'state_id' => 15],
            ['city' => 'Aparecida', 'state_id' => 15],
            ['city' => 'Araçagi', 'state_id' => 15],
            ['city' => 'Arara', 'state_id' => 15],
            ['city' => 'Araruna', 'state_id' => 15],
            ['city' => 'Areia', 'state_id' => 15],
            ['city' => 'Areia de Baraúnas', 'state_id' => 15],
            ['city' => 'Areial', 'state_id' => 15],
            ['city' => 'Aroeiras', 'state_id' => 15],
            ['city' => 'Assunção', 'state_id' => 15],
            ['city' => 'Baía da Traição', 'state_id' => 15],
            ['city' => 'Bananeiras', 'state_id' => 15],
            ['city' => 'Baraúna', 'state_id' => 15],
            ['city' => 'Barra de Santa Rosa', 'state_id' => 15],
            ['city' => 'Barra de Santana', 'state_id' => 15],
            ['city' => 'Barra de São Miguel', 'state_id' => 15],
            ['city' => 'Bayeux', 'state_id' => 15],
            ['city' => 'Belém', 'state_id' => 15],
            ['city' => 'Belém do Brejo do Cruz', 'state_id' => 15],
            ['city' => 'Bernardino Batista', 'state_id' => 15],
            ['city' => 'Boa Ventura', 'state_id' => 15],
            ['city' => 'Boa Vista', 'state_id' => 15],
            ['city' => 'Bom Jesus', 'state_id' => 15],
            ['city' => 'Bom Sucesso', 'state_id' => 15],
            ['city' => 'Bonito de Santa Fé', 'state_id' => 15],
            ['city' => 'Boqueirão', 'state_id' => 15],
            ['city' => 'Borborema', 'state_id' => 15],
            ['city' => 'Brejo do Cruz', 'state_id' => 15],
            ['city' => 'Brejo dos Santos', 'state_id' => 15],
            ['city' => 'Caaporã', 'state_id' => 15],
            ['city' => 'Cabaceiras', 'state_id' => 15],
            ['city' => 'Cabedelo', 'state_id' => 15],
            ['city' => 'Cachoeira dos Índios', 'state_id' => 15],
            ['city' => 'Cacimba de Areia', 'state_id' => 15],
            ['city' => 'Cacimba de Dentro', 'state_id' => 15],
            ['city' => 'Cacimbas', 'state_id' => 15],
            ['city' => 'Caiçara', 'state_id' => 15],
            ['city' => 'Cajazeiras', 'state_id' => 15],
            ['city' => 'Cajazeirinhas', 'state_id' => 15],
            ['city' => 'Caldas Brandão', 'state_id' => 15],
            ['city' => 'Camalaú', 'state_id' => 15],
            ['city' => 'Campina Grande', 'state_id' => 15],
            ['city' => 'Campo de Santana', 'state_id' => 15],
            ['city' => 'Capim', 'state_id' => 15],
            ['city' => 'Caraúbas', 'state_id' => 15],
            ['city' => 'Carrapateira', 'state_id' => 15],
            ['city' => 'Casserengue', 'state_id' => 15],
            ['city' => 'Catingueira', 'state_id' => 15],
            ['city' => 'Catolé do Rocha', 'state_id' => 15],
            ['city' => 'Caturité', 'state_id' => 15],
            ['city' => 'Conceição', 'state_id' => 15],
            ['city' => 'Condado', 'state_id' => 15],
            ['city' => 'Conde', 'state_id' => 15],
            ['city' => 'Congo', 'state_id' => 15],
            ['city' => 'Coremas', 'state_id' => 15],
            ['city' => 'Coxixola', 'state_id' => 15],
            ['city' => 'Cruz do Espírito Santo', 'state_id' => 15],
            ['city' => 'Cubati', 'state_id' => 15],
            ['city' => 'Cuité', 'state_id' => 15],
            ['city' => 'Cuité de Mamanguape', 'state_id' => 15],
            ['city' => 'Cuitegi', 'state_id' => 15],
            ['city' => 'Curral de Cima', 'state_id' => 15],
            ['city' => 'Curral Velho', 'state_id' => 15],
            ['city' => 'Damião', 'state_id' => 15],
            ['city' => 'Desterro', 'state_id' => 15],
            ['city' => 'Diamante', 'state_id' => 15],
            ['city' => 'Dona Inês', 'state_id' => 15],
            ['city' => 'Duas Estradas', 'state_id' => 15],
            ['city' => 'Emas', 'state_id' => 15],
            ['city' => 'Esperança', 'state_id' => 15],
            ['city' => 'Fagundes', 'state_id' => 15],
            ['city' => 'Frei Martinho', 'state_id' => 15],
            ['city' => 'Gado Bravo', 'state_id' => 15],
            ['city' => 'Guarabira', 'state_id' => 15],
            ['city' => 'Gurinhém', 'state_id' => 15],
            ['city' => 'Gurjão', 'state_id' => 15],
            ['city' => 'Ibiara', 'state_id' => 15],
            ['city' => 'Igaracy', 'state_id' => 15],
            ['city' => 'Imaculada', 'state_id' => 15],
            ['city' => 'Ingá', 'state_id' => 15],
            ['city' => 'Itabaiana', 'state_id' => 15],
            ['city' => 'Itaporanga', 'state_id' => 15],
            ['city' => 'Itapororoca', 'state_id' => 15],
            ['city' => 'Itatuba', 'state_id' => 15],
            ['city' => 'Jacaraú', 'state_id' => 15],
            ['city' => 'Jericó', 'state_id' => 15],
            ['city' => 'João Pessoa', 'state_id' => 15],
            ['city' => 'Juarez Távora', 'state_id' => 15],
            ['city' => 'Juazeirinho', 'state_id' => 15],
            ['city' => 'Junco do Seridó', 'state_id' => 15],
            ['city' => 'Juripiranga', 'state_id' => 15],
            ['city' => 'Juru', 'state_id' => 15],
            ['city' => 'Lagoa', 'state_id' => 15],
            ['city' => 'Lagoa de Dentro', 'state_id' => 15],
            ['city' => 'Lagoa Seca', 'state_id' => 15],
            ['city' => 'Lastro', 'state_id' => 15],
            ['city' => 'Livramento', 'state_id' => 15],
            ['city' => 'Logradouro', 'state_id' => 15],
            ['city' => 'Lucena', 'state_id' => 15],
            ['city' => 'Mãe d`Água', 'state_id' => 15],
            ['city' => 'Malta', 'state_id' => 15],
            ['city' => 'Mamanguape', 'state_id' => 15],
            ['city' => 'Manaíra', 'state_id' => 15],
            ['city' => 'Marcação', 'state_id' => 15],
            ['city' => 'Mari', 'state_id' => 15],
            ['city' => 'Marizópolis', 'state_id' => 15],
            ['city' => 'Massaranduba', 'state_id' => 15],
            ['city' => 'Mataraca', 'state_id' => 15],
            ['city' => 'Matinhas', 'state_id' => 15],
            ['city' => 'Mato Grosso', 'state_id' => 15],
            ['city' => 'Maturéia', 'state_id' => 15],
            ['city' => 'Mogeiro', 'state_id' => 15],
            ['city' => 'Montadas', 'state_id' => 15],
            ['city' => 'Monte Horebe', 'state_id' => 15],
            ['city' => 'Monteiro', 'state_id' => 15],
            ['city' => 'Mulungu', 'state_id' => 15],
            ['city' => 'Natuba', 'state_id' => 15],
            ['city' => 'Nazarezinho', 'state_id' => 15],
            ['city' => 'Nova Floresta', 'state_id' => 15],
            ['city' => 'Nova Olinda', 'state_id' => 15],
            ['city' => 'Nova Palmeira', 'state_id' => 15],
            ['city' => 'Olho d`Água', 'state_id' => 15],
            ['city' => 'Olivedos', 'state_id' => 15],
            ['city' => 'Ouro Velho', 'state_id' => 15],
            ['city' => 'Parari', 'state_id' => 15],
            ['city' => 'Passagem', 'state_id' => 15],
            ['city' => 'Patos', 'state_id' => 15],
            ['city' => 'Paulista', 'state_id' => 15],
            ['city' => 'Pedra Branca', 'state_id' => 15],
            ['city' => 'Pedra Lavrada', 'state_id' => 15],
            ['city' => 'Pedras de Fogo', 'state_id' => 15],
            ['city' => 'Pedro Régis', 'state_id' => 15],
            ['city' => 'Piancó', 'state_id' => 15],
            ['city' => 'Picuí', 'state_id' => 15],
            ['city' => 'Pilar', 'state_id' => 15],
            ['city' => 'Pilões', 'state_id' => 15],
            ['city' => 'Pilõezinhos', 'state_id' => 15],
            ['city' => 'Pirpirituba', 'state_id' => 15],
            ['city' => 'Pitimbu', 'state_id' => 15],
            ['city' => 'Pocinhos', 'state_id' => 15],
            ['city' => 'Poço Dantas', 'state_id' => 15],
            ['city' => 'Poço de José de Moura', 'state_id' => 15],
            ['city' => 'Pombal', 'state_id' => 15],
            ['city' => 'Prata', 'state_id' => 15],
            ['city' => 'Princesa Isabel', 'state_id' => 15],
            ['city' => 'Puxinanã', 'state_id' => 15],
            ['city' => 'Queimadas', 'state_id' => 15],
            ['city' => 'Quixabá', 'state_id' => 15],
            ['city' => 'Remígio', 'state_id' => 15],
            ['city' => 'Riachão', 'state_id' => 15],
            ['city' => 'Riachão do Bacamarte', 'state_id' => 15],
            ['city' => 'Riachão do Poço', 'state_id' => 15],
            ['city' => 'Riacho de Santo Antônio', 'state_id' => 15],
            ['city' => 'Riacho dos Cavalos', 'state_id' => 15],
            ['city' => 'Rio Tinto', 'state_id' => 15],
            ['city' => 'Salgadinho', 'state_id' => 15],
            ['city' => 'Salgado de São Félix', 'state_id' => 15],
            ['city' => 'Santa Cecília', 'state_id' => 15],
            ['city' => 'Santa Cruz', 'state_id' => 15],
            ['city' => 'Santa Helena', 'state_id' => 15],
            ['city' => 'Santa Inês', 'state_id' => 15],
            ['city' => 'Santa Luzia', 'state_id' => 15],
            ['city' => 'Santa Rita', 'state_id' => 15],
            ['city' => 'Santa Teresinha', 'state_id' => 15],
            ['city' => 'Santana de Mangueira', 'state_id' => 15],
            ['city' => 'Santana dos Garrotes', 'state_id' => 15],
            ['city' => 'Santarém', 'state_id' => 15],
            ['city' => 'Santo André', 'state_id' => 15],
            ['city' => 'São Bentinho', 'state_id' => 15],
            ['city' => 'São Bento', 'state_id' => 15],
            ['city' => 'São Domingos de Pombal', 'state_id' => 15],
            ['city' => 'São Domingos do Cariri', 'state_id' => 15],
            ['city' => 'São Francisco', 'state_id' => 15],
            ['city' => 'São João do Cariri', 'state_id' => 15],
            ['city' => 'São João do Rio do Peixe', 'state_id' => 15],
            ['city' => 'São João do Tigre', 'state_id' => 15],
            ['city' => 'São José da Lagoa Tapada', 'state_id' => 15],
            ['city' => 'São José de Caiana', 'state_id' => 15],
            ['city' => 'São José de Espinharas', 'state_id' => 15],
            ['city' => 'São José de Piranhas', 'state_id' => 15],
            ['city' => 'São José de Princesa', 'state_id' => 15],
            ['city' => 'São José do Bonfim', 'state_id' => 15],
            ['city' => 'São José do Brejo do Cruz', 'state_id' => 15],
            ['city' => 'São José do Sabugi', 'state_id' => 15],
            ['city' => 'São José dos Cordeiros', 'state_id' => 15],
            ['city' => 'São José dos Ramos', 'state_id' => 15],
            ['city' => 'São Mamede', 'state_id' => 15],
            ['city' => 'São Miguel de Taipu', 'state_id' => 15],
            ['city' => 'São Sebastião de Lagoa de Roça', 'state_id' => 15],
            ['city' => 'São Sebastião do Umbuzeiro', 'state_id' => 15],
            ['city' => 'Sapé', 'state_id' => 15],
            ['city' => 'Seridó', 'state_id' => 15],
            ['city' => 'Serra Branca', 'state_id' => 15],
            ['city' => 'Serra da Raiz', 'state_id' => 15],
            ['city' => 'Serra Grande', 'state_id' => 15],
            ['city' => 'Serra Redonda', 'state_id' => 15],
            ['city' => 'Serraria', 'state_id' => 15],
            ['city' => 'Sertãozinho', 'state_id' => 15],
            ['city' => 'Sobrado', 'state_id' => 15],
            ['city' => 'Solânea', 'state_id' => 15],
            ['city' => 'Soledade', 'state_id' => 15],
            ['city' => 'Sossêgo', 'state_id' => 15],
            ['city' => 'Sousa', 'state_id' => 15],
            ['city' => 'Sumé', 'state_id' => 15],
            ['city' => 'Taperoá', 'state_id' => 15],
            ['city' => 'Tavares', 'state_id' => 15],
            ['city' => 'Teixeira', 'state_id' => 15],
            ['city' => 'Tenório', 'state_id' => 15],
            ['city' => 'Triunfo', 'state_id' => 15],
            ['city' => 'Uiraúna', 'state_id' => 15],
            ['city' => 'Umbuzeiro', 'state_id' => 15],
            ['city' => 'Várzea', 'state_id' => 15],
            ['city' => 'Vieirópolis', 'state_id' => 15],
            ['city' => 'Vista Serrana', 'state_id' => 15],
            ['city' => 'Zabelê', 'state_id' => 15]
        ]);

        $this->command->info('Cidades da Paraíba importadas com sucesso!');
    }
}
