<?php

namespace Database\Seeders\Estados;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CidadesRioGrandeDoSulSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cities')->insert([
        	['city' => 'Aceguá', 'state_id' => 21],
            ['city' => 'Água Santa', 'state_id' => 21],
            ['city' => 'Agudo', 'state_id' => 21],
            ['city' => 'Ajuricaba', 'state_id' => 21],
            ['city' => 'Alecrim', 'state_id' => 21],
            ['city' => 'Alegrete', 'state_id' => 21],
            ['city' => 'Alegria', 'state_id' => 21],
            ['city' => 'Almirante Tamandaré do Sul', 'state_id' => 21],
            ['city' => 'Alpestre', 'state_id' => 21],
            ['city' => 'Alto Alegre', 'state_id' => 21],
            ['city' => 'Alto Feliz', 'state_id' => 21],
            ['city' => 'Alvorada', 'state_id' => 21],
            ['city' => 'Amaral Ferrador', 'state_id' => 21],
            ['city' => 'Ametista do Sul', 'state_id' => 21],
            ['city' => 'André da Rocha', 'state_id' => 21],
            ['city' => 'Anta Gorda', 'state_id' => 21],
            ['city' => 'Antônio Prado', 'state_id' => 21],
            ['city' => 'Arambaré', 'state_id' => 21],
            ['city' => 'Araricá', 'state_id' => 21],
            ['city' => 'Aratiba', 'state_id' => 21],
            ['city' => 'Arroio do Meio', 'state_id' => 21],
            ['city' => 'Arroio do Padre', 'state_id' => 21],
            ['city' => 'Arroio do Sal', 'state_id' => 21],
            ['city' => 'Arroio do Tigre', 'state_id' => 21],
            ['city' => 'Arroio dos Ratos', 'state_id' => 21],
            ['city' => 'Arroio Grande', 'state_id' => 21],
            ['city' => 'Arvorezinha', 'state_id' => 21],
            ['city' => 'Augusto Pestana', 'state_id' => 21],
            ['city' => 'Áurea', 'state_id' => 21],
            ['city' => 'Bagé', 'state_id' => 21],
            ['city' => 'Balneário Pinhal', 'state_id' => 21],
            ['city' => 'Barão', 'state_id' => 21],
            ['city' => 'Barão de Cotegipe', 'state_id' => 21],
            ['city' => 'Barão do Triunfo', 'state_id' => 21],
            ['city' => 'Barra do Guarita', 'state_id' => 21],
            ['city' => 'Barra do Quaraí', 'state_id' => 21],
            ['city' => 'Barra do Ribeiro', 'state_id' => 21],
            ['city' => 'Barra do Rio Azul', 'state_id' => 21],
            ['city' => 'Barra Funda', 'state_id' => 21],
            ['city' => 'Barracão', 'state_id' => 21],
            ['city' => 'Barros Cassal', 'state_id' => 21],
            ['city' => 'Benjamin Constant do Sul', 'state_id' => 21],
            ['city' => 'Bento Gonçalves', 'state_id' => 21],
            ['city' => 'Boa Vista das Missões', 'state_id' => 21],
            ['city' => 'Boa Vista do Buricá', 'state_id' => 21],
            ['city' => 'Boa Vista do Cadeado', 'state_id' => 21],
            ['city' => 'Boa Vista do Incra', 'state_id' => 21],
            ['city' => 'Boa Vista do Sul', 'state_id' => 21],
            ['city' => 'Bom Jesus', 'state_id' => 21],
            ['city' => 'Bom Princípio', 'state_id' => 21],
            ['city' => 'Bom Progresso', 'state_id' => 21],
            ['city' => 'Bom Retiro do Sul', 'state_id' => 21],
            ['city' => 'Boqueirão do Leão', 'state_id' => 21],
            ['city' => 'Bossoroca', 'state_id' => 21],
            ['city' => 'Bozano', 'state_id' => 21],
            ['city' => 'Braga', 'state_id' => 21],
            ['city' => 'Brochier', 'state_id' => 21],
            ['city' => 'Butiá', 'state_id' => 21],
            ['city' => 'Caçapava do Sul', 'state_id' => 21],
            ['city' => 'Cacequi', 'state_id' => 21],
            ['city' => 'Cachoeira do Sul', 'state_id' => 21],
            ['city' => 'Cachoeirinha', 'state_id' => 21],
            ['city' => 'Cacique Doble', 'state_id' => 21],
            ['city' => 'Caibaté', 'state_id' => 21],
            ['city' => 'Caiçara', 'state_id' => 21],
            ['city' => 'Camaquã', 'state_id' => 21],
            ['city' => 'Camargo', 'state_id' => 21],
            ['city' => 'Cambará do Sul', 'state_id' => 21],
            ['city' => 'Campestre da Serra', 'state_id' => 21],
            ['city' => 'Campina das Missões', 'state_id' => 21],
            ['city' => 'Campinas do Sul', 'state_id' => 21],
            ['city' => 'Campo Bom', 'state_id' => 21],
            ['city' => 'Campo Novo', 'state_id' => 21],
            ['city' => 'Campos Borges', 'state_id' => 21],
            ['city' => 'Candelária', 'state_id' => 21],
            ['city' => 'Cândido Godói', 'state_id' => 21],
            ['city' => 'Candiota', 'state_id' => 21],
            ['city' => 'Canela', 'state_id' => 21],
            ['city' => 'Canguçu', 'state_id' => 21],
            ['city' => 'Canoas', 'state_id' => 21],
            ['city' => 'Canudos do Vale', 'state_id' => 21],
            ['city' => 'Capão Bonito do Sul', 'state_id' => 21],
            ['city' => 'Capão da Canoa', 'state_id' => 21],
            ['city' => 'Capão do Cipó', 'state_id' => 21],
            ['city' => 'Capão do Leão', 'state_id' => 21],
            ['city' => 'Capela de Santana', 'state_id' => 21],
            ['city' => 'Capitão', 'state_id' => 21],
            ['city' => 'Capivari do Sul', 'state_id' => 21],
            ['city' => 'Caraá', 'state_id' => 21],
            ['city' => 'Carazinho', 'state_id' => 21],
            ['city' => 'Carlos Barbosa', 'state_id' => 21],
            ['city' => 'Carlos Gomes', 'state_id' => 21],
            ['city' => 'Casca', 'state_id' => 21],
            ['city' => 'Caseiros', 'state_id' => 21],
            ['city' => 'Catuípe', 'state_id' => 21],
            ['city' => 'Caxias do Sul', 'state_id' => 21],
            ['city' => 'Centenário', 'state_id' => 21],
            ['city' => 'Cerrito', 'state_id' => 21],
            ['city' => 'Cerro Branco', 'state_id' => 21],
            ['city' => 'Cerro Grande', 'state_id' => 21],
            ['city' => 'Cerro Grande do Sul', 'state_id' => 21],
            ['city' => 'Cerro Largo', 'state_id' => 21],
            ['city' => 'Chapada', 'state_id' => 21],
            ['city' => 'Charqueadas', 'state_id' => 21],
            ['city' => 'Charrua', 'state_id' => 21],
            ['city' => 'Chiapeta', 'state_id' => 21],
            ['city' => 'Chuí', 'state_id' => 21],
            ['city' => 'Chuvisca', 'state_id' => 21],
            ['city' => 'Cidreira', 'state_id' => 21],
            ['city' => 'Ciríaco', 'state_id' => 21],
            ['city' => 'Colinas', 'state_id' => 21],
            ['city' => 'Colorado', 'state_id' => 21],
            ['city' => 'Condor', 'state_id' => 21],
            ['city' => 'Constantina', 'state_id' => 21],
            ['city' => 'Coqueiro Baixo', 'state_id' => 21],
            ['city' => 'Coqueiros do Sul', 'state_id' => 21],
            ['city' => 'Coronel Barros', 'state_id' => 21],
            ['city' => 'Coronel Bicaco', 'state_id' => 21],
            ['city' => 'Coronel Pilar', 'state_id' => 21],
            ['city' => 'Cotiporã', 'state_id' => 21],
            ['city' => 'Coxilha', 'state_id' => 21],
            ['city' => 'Crissiumal', 'state_id' => 21],
            ['city' => 'Cristal', 'state_id' => 21],
            ['city' => 'Cristal do Sul', 'state_id' => 21],
            ['city' => 'Cruz Alta', 'state_id' => 21],
            ['city' => 'Cruzaltense', 'state_id' => 21],
            ['city' => 'Cruzeiro do Sul', 'state_id' => 21],
            ['city' => 'David Canabarro', 'state_id' => 21],
            ['city' => 'Derrubadas', 'state_id' => 21],
            ['city' => 'Dezesseis de Novembro', 'state_id' => 21],
            ['city' => 'Dilermando de Aguiar', 'state_id' => 21],
            ['city' => 'Dois Irmãos', 'state_id' => 21],
            ['city' => 'Dois Irmãos das Missões', 'state_id' => 21],
            ['city' => 'Dois Lajeados', 'state_id' => 21],
            ['city' => 'Dom Feliciano', 'state_id' => 21],
            ['city' => 'Dom Pedrito', 'state_id' => 21],
            ['city' => 'Dom Pedro de Alcântara', 'state_id' => 21],
            ['city' => 'Dona Francisca', 'state_id' => 21],
            ['city' => 'Doutor Maurício Cardoso', 'state_id' => 21],
            ['city' => 'Doutor Ricardo', 'state_id' => 21],
            ['city' => 'Eldorado do Sul', 'state_id' => 21],
            ['city' => 'Encantado', 'state_id' => 21],
            ['city' => 'Encruzilhada do Sul', 'state_id' => 21],
            ['city' => 'Engenho Velho', 'state_id' => 21],
            ['city' => 'Entre Rios do Sul', 'state_id' => 21],
            ['city' => 'Entre-Ijuís', 'state_id' => 21],
            ['city' => 'Erebango', 'state_id' => 21],
            ['city' => 'Erechim', 'state_id' => 21],
            ['city' => 'Ernestina', 'state_id' => 21],
            ['city' => 'Erval Grande', 'state_id' => 21],
            ['city' => 'Erval Seco', 'state_id' => 21],
            ['city' => 'Esmeralda', 'state_id' => 21],
            ['city' => 'Esperança do Sul', 'state_id' => 21],
            ['city' => 'Espumoso', 'state_id' => 21],
            ['city' => 'Estação', 'state_id' => 21],
            ['city' => 'Estância Velha', 'state_id' => 21],
            ['city' => 'Esteio', 'state_id' => 21],
            ['city' => 'Estrela', 'state_id' => 21],
            ['city' => 'Estrela Velha', 'state_id' => 21],
            ['city' => 'Eugênio de Castro', 'state_id' => 21],
            ['city' => 'Fagundes Varela', 'state_id' => 21],
            ['city' => 'Farroupilha', 'state_id' => 21],
            ['city' => 'Faxinal do Soturno', 'state_id' => 21],
            ['city' => 'Faxinalzinho', 'state_id' => 21],
            ['city' => 'Fazenda Vilanova', 'state_id' => 21],
            ['city' => 'Feliz', 'state_id' => 21],
            ['city' => 'Flores da Cunha', 'state_id' => 21],
            ['city' => 'Floriano Peixoto', 'state_id' => 21],
            ['city' => 'Fontoura Xavier', 'state_id' => 21],
            ['city' => 'Formigueiro', 'state_id' => 21],
            ['city' => 'Forquetinha', 'state_id' => 21],
            ['city' => 'Fortaleza dos Valos', 'state_id' => 21],
            ['city' => 'Frederico Westphalen', 'state_id' => 21],
            ['city' => 'Garibaldi', 'state_id' => 21],
            ['city' => 'Garruchos', 'state_id' => 21],
            ['city' => 'Gaurama', 'state_id' => 21],
            ['city' => 'General Câmara', 'state_id' => 21],
            ['city' => 'Gentil', 'state_id' => 21],
            ['city' => 'Getúlio Vargas', 'state_id' => 21],
            ['city' => 'Giruá', 'state_id' => 21],
            ['city' => 'Glorinha', 'state_id' => 21],
            ['city' => 'Gramado', 'state_id' => 21],
            ['city' => 'Gramado dos Loureiros', 'state_id' => 21],
            ['city' => 'Gramado Xavier', 'state_id' => 21],
            ['city' => 'Gravataí', 'state_id' => 21],
            ['city' => 'Guabiju', 'state_id' => 21],
            ['city' => 'Guaíba', 'state_id' => 21],
            ['city' => 'Guaporé', 'state_id' => 21],
            ['city' => 'Guarani das Missões', 'state_id' => 21],
            ['city' => 'Harmonia', 'state_id' => 21],
            ['city' => 'Herval', 'state_id' => 21],
            ['city' => 'Herveiras', 'state_id' => 21],
            ['city' => 'Horizontina', 'state_id' => 21],
            ['city' => 'Hulha Negra', 'state_id' => 21],
            ['city' => 'Humaitá', 'state_id' => 21],
            ['city' => 'Ibarama', 'state_id' => 21],
            ['city' => 'Ibiaçá', 'state_id' => 21],
            ['city' => 'Ibiraiaras', 'state_id' => 21],
            ['city' => 'Ibirapuitã', 'state_id' => 21],
            ['city' => 'Ibirubá', 'state_id' => 21],
            ['city' => 'Igrejinha', 'state_id' => 21],
            ['city' => 'Ijuí', 'state_id' => 21],
            ['city' => 'Ilópolis', 'state_id' => 21],
            ['city' => 'Imbé', 'state_id' => 21],
            ['city' => 'Imigrante', 'state_id' => 21],
            ['city' => 'Independência', 'state_id' => 21],
            ['city' => 'Inhacorá', 'state_id' => 21],
            ['city' => 'Ipê', 'state_id' => 21],
            ['city' => 'Ipiranga do Sul', 'state_id' => 21],
            ['city' => 'Iraí', 'state_id' => 21],
            ['city' => 'Itaara', 'state_id' => 21],
            ['city' => 'Itacurubi', 'state_id' => 21],
            ['city' => 'Itapuca', 'state_id' => 21],
            ['city' => 'Itaqui', 'state_id' => 21],
            ['city' => 'Itati', 'state_id' => 21],
            ['city' => 'Itatiba do Sul', 'state_id' => 21],
            ['city' => 'Ivorá', 'state_id' => 21],
            ['city' => 'Ivoti', 'state_id' => 21],
            ['city' => 'Jaboticaba', 'state_id' => 21],
            ['city' => 'Jacuizinho', 'state_id' => 21],
            ['city' => 'Jacutinga', 'state_id' => 21],
            ['city' => 'Jaguarão', 'state_id' => 21],
            ['city' => 'Jaguari', 'state_id' => 21],
            ['city' => 'Jaquirana', 'state_id' => 21],
            ['city' => 'Jari', 'state_id' => 21],
            ['city' => 'Jóia', 'state_id' => 21],
            ['city' => 'Júlio de Castilhos', 'state_id' => 21],
            ['city' => 'Lagoa Bonita do Sul', 'state_id' => 21],
            ['city' => 'Lagoa dos Três Cantos', 'state_id' => 21],
            ['city' => 'Lagoa Vermelha', 'state_id' => 21],
            ['city' => 'Lagoão', 'state_id' => 21],
            ['city' => 'Lajeado', 'state_id' => 21],
            ['city' => 'Lajeado do Bugre', 'state_id' => 21],
            ['city' => 'Lavras do Sul', 'state_id' => 21],
            ['city' => 'Liberato Salzano', 'state_id' => 21],
            ['city' => 'Lindolfo Collor', 'state_id' => 21],
            ['city' => 'Linha Nova', 'state_id' => 21],
            ['city' => 'Maçambara', 'state_id' => 21],
            ['city' => 'Machadinho', 'state_id' => 21],
            ['city' => 'Mampituba', 'state_id' => 21],
            ['city' => 'Manoel Viana', 'state_id' => 21],
            ['city' => 'Maquiné', 'state_id' => 21],
            ['city' => 'Maratá', 'state_id' => 21],
            ['city' => 'Marau', 'state_id' => 21],
            ['city' => 'Marcelino Ramos', 'state_id' => 21],
            ['city' => 'Mariana Pimentel', 'state_id' => 21],
            ['city' => 'Mariano Moro', 'state_id' => 21],
            ['city' => 'Marques de Souza', 'state_id' => 21],
            ['city' => 'Mata', 'state_id' => 21],
            ['city' => 'Mato Castelhano', 'state_id' => 21],
            ['city' => 'Mato Leitão', 'state_id' => 21],
            ['city' => 'Mato Queimado', 'state_id' => 21],
            ['city' => 'Maximiliano de Almeida', 'state_id' => 21],
            ['city' => 'Minas do Leão', 'state_id' => 21],
            ['city' => 'Miraguaí', 'state_id' => 21],
            ['city' => 'Montauri', 'state_id' => 21],
            ['city' => 'Monte Alegre dos Campos', 'state_id' => 21],
            ['city' => 'Monte Belo do Sul', 'state_id' => 21],
            ['city' => 'Montenegro', 'state_id' => 21],
            ['city' => 'Mormaço', 'state_id' => 21],
            ['city' => 'Morrinhos do Sul', 'state_id' => 21],
            ['city' => 'Morro Redondo', 'state_id' => 21],
            ['city' => 'Morro Reuter', 'state_id' => 21],
            ['city' => 'Mostardas', 'state_id' => 21],
            ['city' => 'Muçum', 'state_id' => 21],
            ['city' => 'Muitos Capões', 'state_id' => 21],
            ['city' => 'Muliterno', 'state_id' => 21],
            ['city' => 'Não-Me-Toque', 'state_id' => 21],
            ['city' => 'Nicolau Vergueiro', 'state_id' => 21],
            ['city' => 'Nonoai', 'state_id' => 21],
            ['city' => 'Nova Alvorada', 'state_id' => 21],
            ['city' => 'Nova Araçá', 'state_id' => 21],
            ['city' => 'Nova Bassano', 'state_id' => 21],
            ['city' => 'Nova Boa Vista', 'state_id' => 21],
            ['city' => 'Nova Bréscia', 'state_id' => 21],
            ['city' => 'Nova Candelária', 'state_id' => 21],
            ['city' => 'Nova Esperança do Sul', 'state_id' => 21],
            ['city' => 'Nova Hartz', 'state_id' => 21],
            ['city' => 'Nova Pádua', 'state_id' => 21],
            ['city' => 'Nova Palma', 'state_id' => 21],
            ['city' => 'Nova Petrópolis', 'state_id' => 21],
            ['city' => 'Nova Prata', 'state_id' => 21],
            ['city' => 'Nova Ramada', 'state_id' => 21],
            ['city' => 'Nova Roma do Sul', 'state_id' => 21],
            ['city' => 'Nova Santa Rita', 'state_id' => 21],
            ['city' => 'Novo Barreiro', 'state_id' => 21],
            ['city' => 'Novo Cabrais', 'state_id' => 21],
            ['city' => 'Novo Hamburgo', 'state_id' => 21],
            ['city' => 'Novo Machado', 'state_id' => 21],
            ['city' => 'Novo Tiradentes', 'state_id' => 21],
            ['city' => 'Novo Xingu', 'state_id' => 21],
            ['city' => 'Osório', 'state_id' => 21],
            ['city' => 'Paim Filho', 'state_id' => 21],
            ['city' => 'Palmares do Sul', 'state_id' => 21],
            ['city' => 'Palmeira das Missões', 'state_id' => 21],
            ['city' => 'Palmitinho', 'state_id' => 21],
            ['city' => 'Panambi', 'state_id' => 21],
            ['city' => 'Pantano Grande', 'state_id' => 21],
            ['city' => 'Paraí', 'state_id' => 21],
            ['city' => 'Paraíso do Sul', 'state_id' => 21],
            ['city' => 'Pareci Novo', 'state_id' => 21],
            ['city' => 'Parobé', 'state_id' => 21],
            ['city' => 'Passa Sete', 'state_id' => 21],
            ['city' => 'Passo do Sobrado', 'state_id' => 21],
            ['city' => 'Passo Fundo', 'state_id' => 21],
            ['city' => 'Paulo Bento', 'state_id' => 21],
            ['city' => 'Paverama', 'state_id' => 21],
            ['city' => 'Pedras Altas', 'state_id' => 21],
            ['city' => 'Pedro Osório', 'state_id' => 21],
            ['city' => 'Pejuçara', 'state_id' => 21],
            ['city' => 'Pelotas', 'state_id' => 21],
            ['city' => 'Picada Café', 'state_id' => 21],
            ['city' => 'Pinhal', 'state_id' => 21],
            ['city' => 'Pinhal da Serra', 'state_id' => 21],
            ['city' => 'Pinhal Grande', 'state_id' => 21],
            ['city' => 'Pinheirinho do Vale', 'state_id' => 21],
            ['city' => 'Pinheiro Machado', 'state_id' => 21],
            ['city' => 'Pirapó', 'state_id' => 21],
            ['city' => 'Piratini', 'state_id' => 21],
            ['city' => 'Planalto', 'state_id' => 21],
            ['city' => 'Poço das Antas', 'state_id' => 21],
            ['city' => 'Pontão', 'state_id' => 21],
            ['city' => 'Ponte Preta', 'state_id' => 21],
            ['city' => 'Portão', 'state_id' => 21],
            ['city' => 'Porto Alegre', 'state_id' => 21],
            ['city' => 'Porto Lucena', 'state_id' => 21],
            ['city' => 'Porto Mauá', 'state_id' => 21],
            ['city' => 'Porto Vera Cruz', 'state_id' => 21],
            ['city' => 'Porto Xavier', 'state_id' => 21],
            ['city' => 'Pouso Novo', 'state_id' => 21],
            ['city' => 'Presidente Lucena', 'state_id' => 21],
            ['city' => 'Progresso', 'state_id' => 21],
            ['city' => 'Protásio Alves', 'state_id' => 21],
            ['city' => 'Putinga', 'state_id' => 21],
            ['city' => 'Quaraí', 'state_id' => 21],
            ['city' => 'Quatro Irmãos', 'state_id' => 21],
            ['city' => 'Quevedos', 'state_id' => 21],
            ['city' => 'Quinze de Novembro', 'state_id' => 21],
            ['city' => 'Redentora', 'state_id' => 21],
            ['city' => 'Relvado', 'state_id' => 21],
            ['city' => 'Restinga Seca', 'state_id' => 21],
            ['city' => 'Rio dos Índios', 'state_id' => 21],
            ['city' => 'Rio Grande', 'state_id' => 21],
            ['city' => 'Rio Pardo', 'state_id' => 21],
            ['city' => 'Riozinho', 'state_id' => 21],
            ['city' => 'Roca Sales', 'state_id' => 21],
            ['city' => 'Rodeio Bonito', 'state_id' => 21],
            ['city' => 'Rolador', 'state_id' => 21],
            ['city' => 'Rolante', 'state_id' => 21],
            ['city' => 'Ronda Alta', 'state_id' => 21],
            ['city' => 'Rondinha', 'state_id' => 21],
            ['city' => 'Roque Gonzales', 'state_id' => 21],
            ['city' => 'Rosário do Sul', 'state_id' => 21],
            ['city' => 'Sagrada Família', 'state_id' => 21],
            ['city' => 'Saldanha Marinho', 'state_id' => 21],
            ['city' => 'Salto do Jacuí', 'state_id' => 21],
            ['city' => 'Salvador das Missões', 'state_id' => 21],
            ['city' => 'Salvador do Sul', 'state_id' => 21],
            ['city' => 'Sananduva', 'state_id' => 21],
            ['city' => 'Santa Bárbara do Sul', 'state_id' => 21],
            ['city' => 'Santa Cecília do Sul', 'state_id' => 21],
            ['city' => 'Santa Clara do Sul', 'state_id' => 21],
            ['city' => 'Santa Cruz do Sul', 'state_id' => 21],
            ['city' => 'Santa Margarida do Sul', 'state_id' => 21],
            ['city' => 'Santa Maria', 'state_id' => 21],
            ['city' => 'Santa Maria do Herval', 'state_id' => 21],
            ['city' => 'Santa Rosa', 'state_id' => 21],
            ['city' => 'Santa Tereza', 'state_id' => 21],
            ['city' => 'Santa Vitória do Palmar', 'state_id' => 21],
            ['city' => 'Santana da Boa Vista', 'state_id' => 21],
            ['city' => 'Santana do Livramento', 'state_id' => 21],
            ['city' => 'Santiago', 'state_id' => 21],
            ['city' => 'Santo Ângelo', 'state_id' => 21],
            ['city' => 'Santo Antônio da Patrulha', 'state_id' => 21],
            ['city' => 'Santo Antônio das Missões', 'state_id' => 21],
            ['city' => 'Santo Antônio do Palma', 'state_id' => 21],
            ['city' => 'Santo Antônio do Planalto', 'state_id' => 21],
            ['city' => 'Santo Augusto', 'state_id' => 21],
            ['city' => 'Santo Cristo', 'state_id' => 21],
            ['city' => 'Santo Expedito do Sul', 'state_id' => 21],
            ['city' => 'São Borja', 'state_id' => 21],
            ['city' => 'São Domingos do Sul', 'state_id' => 21],
            ['city' => 'São Francisco de Assis', 'state_id' => 21],
            ['city' => 'São Francisco de Paula', 'state_id' => 21],
            ['city' => 'São Gabriel', 'state_id' => 21],
            ['city' => 'São Jerônimo', 'state_id' => 21],
            ['city' => 'São João da Urtiga', 'state_id' => 21],
            ['city' => 'São João do Polêsine', 'state_id' => 21],
            ['city' => 'São Jorge', 'state_id' => 21],
            ['city' => 'São José das Missões', 'state_id' => 21],
            ['city' => 'São José do Herval', 'state_id' => 21],
            ['city' => 'São José do Hortêncio', 'state_id' => 21],
            ['city' => 'São José do Inhacorá', 'state_id' => 21],
            ['city' => 'São José do Norte', 'state_id' => 21],
            ['city' => 'São José do Ouro', 'state_id' => 21],
            ['city' => 'São José do Sul', 'state_id' => 21],
            ['city' => 'São José dos Ausentes', 'state_id' => 21],
            ['city' => 'São Leopoldo', 'state_id' => 21],
            ['city' => 'São Lourenço do Sul', 'state_id' => 21],
            ['city' => 'São Luiz Gonzaga', 'state_id' => 21],
            ['city' => 'São Marcos', 'state_id' => 21],
            ['city' => 'São Martinho', 'state_id' => 21],
            ['city' => 'São Martinho da Serra', 'state_id' => 21],
            ['city' => 'São Miguel das Missões', 'state_id' => 21],
            ['city' => 'São Nicolau', 'state_id' => 21],
            ['city' => 'São Paulo das Missões', 'state_id' => 21],
            ['city' => 'São Pedro da Serra', 'state_id' => 21],
            ['city' => 'São Pedro das Missões', 'state_id' => 21],
            ['city' => 'São Pedro do Butiá', 'state_id' => 21],
            ['city' => 'São Pedro do Sul', 'state_id' => 21],
            ['city' => 'São Sebastião do Caí', 'state_id' => 21],
            ['city' => 'São Sepé', 'state_id' => 21],
            ['city' => 'São Valentim', 'state_id' => 21],
            ['city' => 'São Valentim do Sul', 'state_id' => 21],
            ['city' => 'São Valério do Sul', 'state_id' => 21],
            ['city' => 'São Vendelino', 'state_id' => 21],
            ['city' => 'São Vicente do Sul', 'state_id' => 21],
            ['city' => 'Sapiranga', 'state_id' => 21],
            ['city' => 'Sapucaia do Sul', 'state_id' => 21],
            ['city' => 'Sarandi', 'state_id' => 21],
            ['city' => 'Seberi', 'state_id' => 21],
            ['city' => 'Sede Nova', 'state_id' => 21],
            ['city' => 'Segredo', 'state_id' => 21],
            ['city' => 'Selbach', 'state_id' => 21],
            ['city' => 'Senador Salgado Filho', 'state_id' => 21],
            ['city' => 'Sentinela do Sul', 'state_id' => 21],
            ['city' => 'Serafina Corrêa', 'state_id' => 21],
            ['city' => 'Sério', 'state_id' => 21],
            ['city' => 'Sertão', 'state_id' => 21],
            ['city' => 'Sertão Santana', 'state_id' => 21],
            ['city' => 'Sete de Setembro', 'state_id' => 21],
            ['city' => 'Severiano de Almeida', 'state_id' => 21],
            ['city' => 'Silveira Martins', 'state_id' => 21],
            ['city' => 'Sinimbu', 'state_id' => 21],
            ['city' => 'Sobradinho', 'state_id' => 21],
            ['city' => 'Soledade', 'state_id' => 21],
            ['city' => 'Tabaí', 'state_id' => 21],
            ['city' => 'Tapejara', 'state_id' => 21],
            ['city' => 'Tapera', 'state_id' => 21],
            ['city' => 'Tapes', 'state_id' => 21],
            ['city' => 'Taquara', 'state_id' => 21],
            ['city' => 'Taquari', 'state_id' => 21],
            ['city' => 'Taquaruçu do Sul', 'state_id' => 21],
            ['city' => 'Tavares', 'state_id' => 21],
            ['city' => 'Tenente Portela', 'state_id' => 21],
            ['city' => 'Terra de Areia', 'state_id' => 21],
            ['city' => 'Teutônia', 'state_id' => 21],
            ['city' => 'Tio Hugo', 'state_id' => 21],
            ['city' => 'Tiradentes do Sul', 'state_id' => 21],
            ['city' => 'Toropi', 'state_id' => 21],
            ['city' => 'Torres', 'state_id' => 21],
            ['city' => 'Tramandaí', 'state_id' => 21],
            ['city' => 'Travesseiro', 'state_id' => 21],
            ['city' => 'Três Arroios', 'state_id' => 21],
            ['city' => 'Três Cachoeiras', 'state_id' => 21],
            ['city' => 'Três Coroas', 'state_id' => 21],
            ['city' => 'Três de Maio', 'state_id' => 21],
            ['city' => 'Três Forquilhas', 'state_id' => 21],
            ['city' => 'Três Palmeiras', 'state_id' => 21],
            ['city' => 'Três Passos', 'state_id' => 21],
            ['city' => 'Trindade do Sul', 'state_id' => 21],
            ['city' => 'Triunfo', 'state_id' => 21],
            ['city' => 'Tucunduva', 'state_id' => 21],
            ['city' => 'Tunas', 'state_id' => 21],
            ['city' => 'Tupanci do Sul', 'state_id' => 21],
            ['city' => 'Tupanciretã', 'state_id' => 21],
            ['city' => 'Tupandi', 'state_id' => 21],
            ['city' => 'Tuparendi', 'state_id' => 21],
            ['city' => 'Turuçu', 'state_id' => 21],
            ['city' => 'Ubiretama', 'state_id' => 21],
            ['city' => 'União da Serra', 'state_id' => 21],
            ['city' => 'Unistalda', 'state_id' => 21],
            ['city' => 'Uruguaiana', 'state_id' => 21],
            ['city' => 'Vacaria', 'state_id' => 21],
            ['city' => 'Vale do Sol', 'state_id' => 21],
            ['city' => 'Vale Real', 'state_id' => 21],
            ['city' => 'Vale Verde', 'state_id' => 21],
            ['city' => 'Vanini', 'state_id' => 21],
            ['city' => 'Venâncio Aires', 'state_id' => 21],
            ['city' => 'Vera Cruz', 'state_id' => 21],
            ['city' => 'Veranópolis', 'state_id' => 21],
            ['city' => 'Vespasiano Correa', 'state_id' => 21],
            ['city' => 'Viadutos', 'state_id' => 21],
            ['city' => 'Viamão', 'state_id' => 21],
            ['city' => 'Vicente Dutra', 'state_id' => 21],
            ['city' => 'Victor Graeff', 'state_id' => 21],
            ['city' => 'Vila Flores', 'state_id' => 21],
            ['city' => 'Vila Lângaro', 'state_id' => 21],
            ['city' => 'Vila Maria', 'state_id' => 21],
            ['city' => 'Vila Nova do Sul', 'state_id' => 21],
            ['city' => 'Vista Alegre', 'state_id' => 21],
            ['city' => 'Vista Alegre do Prata', 'state_id' => 21],
            ['city' => 'Vista Gaúcha', 'state_id' => 21],
            ['city' => 'Vitória das Missões', 'state_id' => 21],
            ['city' => 'Westfália', 'state_id' => 21],
            ['city' => 'Xangri-lá', 'state_id' => 21]
        ]);

        $this->command->info('Cidades do Rio Grande do Sul importadas com sucesso!');
    }
}
