<?php

namespace Database\Seeders\Estados;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CidadesSantaCatarinaSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cities')->insert([
        	['city' => 'Abdon Batista', 'state_id' => 24],
            ['city' => 'Abelardo Luz', 'state_id' => 24],
            ['city' => 'Agrolândia', 'state_id' => 24],
            ['city' => 'Agronômica', 'state_id' => 24],
            ['city' => 'Água Doce', 'state_id' => 24],
            ['city' => 'Águas de Chapecó', 'state_id' => 24],
            ['city' => 'Águas Frias', 'state_id' => 24],
            ['city' => 'Águas Mornas', 'state_id' => 24],
            ['city' => 'Alfredo Wagner', 'state_id' => 24],
            ['city' => 'Alto Bela Vista', 'state_id' => 24],
            ['city' => 'Anchieta', 'state_id' => 24],
            ['city' => 'Angelina', 'state_id' => 24],
            ['city' => 'Anita Garibaldi', 'state_id' => 24],
            ['city' => 'Anitápolis', 'state_id' => 24],
            ['city' => 'Antônio Carlos', 'state_id' => 24],
            ['city' => 'Apiúna', 'state_id' => 24],
            ['city' => 'Arabutã', 'state_id' => 24],
            ['city' => 'Araquari', 'state_id' => 24],
            ['city' => 'Araranguá', 'state_id' => 24],
            ['city' => 'Armazém', 'state_id' => 24],
            ['city' => 'Arroio Trinta', 'state_id' => 24],
            ['city' => 'Arvoredo', 'state_id' => 24],
            ['city' => 'Ascurra', 'state_id' => 24],
            ['city' => 'Atalanta', 'state_id' => 24],
            ['city' => 'Aurora', 'state_id' => 24],
            ['city' => 'Balneário Arroio do Silva', 'state_id' => 24],
            ['city' => 'Balneário Barra do Sul', 'state_id' => 24],
            ['city' => 'Balneário Camboriú', 'state_id' => 24],
            ['city' => 'Balneário Gaivota', 'state_id' => 24],
            ['city' => 'Bandeirante', 'state_id' => 24],
            ['city' => 'Barra Bonita', 'state_id' => 24],
            ['city' => 'Barra Velha', 'state_id' => 24],
            ['city' => 'Bela Vista do Toldo', 'state_id' => 24],
            ['city' => 'Belmonte', 'state_id' => 24],
            ['city' => 'Benedito Novo', 'state_id' => 24],
            ['city' => 'Biguaçu', 'state_id' => 24],
            ['city' => 'Blumenau', 'state_id' => 24],
            ['city' => 'Bocaina do Sul', 'state_id' => 24],
            ['city' => 'Bom Jardim da Serra', 'state_id' => 24],
            ['city' => 'Bom Jesus', 'state_id' => 24],
            ['city' => 'Bom Jesus do Oeste', 'state_id' => 24],
            ['city' => 'Bom Retiro', 'state_id' => 24],
            ['city' => 'Bombinhas', 'state_id' => 24],
            ['city' => 'Botuverá', 'state_id' => 24],
            ['city' => 'Braço do Norte', 'state_id' => 24],
            ['city' => 'Braço do Trombudo', 'state_id' => 24],
            ['city' => 'Brunópolis', 'state_id' => 24],
            ['city' => 'Brusque', 'state_id' => 24],
            ['city' => 'Caçador', 'state_id' => 24],
            ['city' => 'Caibi', 'state_id' => 24],
            ['city' => 'Calmon', 'state_id' => 24],
            ['city' => 'Camboriú', 'state_id' => 24],
            ['city' => 'Campo Alegre', 'state_id' => 24],
            ['city' => 'Campo Belo do Sul', 'state_id' => 24],
            ['city' => 'Campo Erê', 'state_id' => 24],
            ['city' => 'Campos Novos', 'state_id' => 24],
            ['city' => 'Canelinha', 'state_id' => 24],
            ['city' => 'Canoinhas', 'state_id' => 24],
            ['city' => 'Capão Alto', 'state_id' => 24],
            ['city' => 'Capinzal', 'state_id' => 24],
            ['city' => 'Capivari de Baixo', 'state_id' => 24],
            ['city' => 'Catanduvas', 'state_id' => 24],
            ['city' => 'Caxambu do Sul', 'state_id' => 24],
            ['city' => 'Celso Ramos', 'state_id' => 24],
            ['city' => 'Cerro Negro', 'state_id' => 24],
            ['city' => 'Chapadão do Lageado', 'state_id' => 24],
            ['city' => 'Chapecó', 'state_id' => 24],
            ['city' => 'Cocal do Sul', 'state_id' => 24],
            ['city' => 'Concórdia', 'state_id' => 24],
            ['city' => 'Cordilheira Alta', 'state_id' => 24],
            ['city' => 'Coronel Freitas', 'state_id' => 24],
            ['city' => 'Coronel Martins', 'state_id' => 24],
            ['city' => 'Correia Pinto', 'state_id' => 24],
            ['city' => 'Corupá', 'state_id' => 24],
            ['city' => 'Criciúma', 'state_id' => 24],
            ['city' => 'Cunha Porã', 'state_id' => 24],
            ['city' => 'Cunhataí', 'state_id' => 24],
            ['city' => 'Curitibanos', 'state_id' => 24],
            ['city' => 'Descanso', 'state_id' => 24],
            ['city' => 'Dionísio Cerqueira', 'state_id' => 24],
            ['city' => 'Dona Emma', 'state_id' => 24],
            ['city' => 'Doutor Pedrinho', 'state_id' => 24],
            ['city' => 'Entre Rios', 'state_id' => 24],
            ['city' => 'Ermo', 'state_id' => 24],
            ['city' => 'Erval Velho', 'state_id' => 24],
            ['city' => 'Faxinal dos Guedes', 'state_id' => 24],
            ['city' => 'Flor do Sertão', 'state_id' => 24],
            ['city' => 'Florianópolis', 'state_id' => 24],
            ['city' => 'Formosa do Sul', 'state_id' => 24],
            ['city' => 'Forquilhinha', 'state_id' => 24],
            ['city' => 'Fraiburgo', 'state_id' => 24],
            ['city' => 'Frei Rogério', 'state_id' => 24],
            ['city' => 'Galvão', 'state_id' => 24],
            ['city' => 'Garopaba', 'state_id' => 24],
            ['city' => 'Garuva', 'state_id' => 24],
            ['city' => 'Gaspar', 'state_id' => 24],
            ['city' => 'Governador Celso Ramos', 'state_id' => 24],
            ['city' => 'Grão Pará', 'state_id' => 24],
            ['city' => 'Gravatal', 'state_id' => 24],
            ['city' => 'Guabiruba', 'state_id' => 24],
            ['city' => 'Guaraciaba', 'state_id' => 24],
            ['city' => 'Guaramirim', 'state_id' => 24],
            ['city' => 'Guarujá do Sul', 'state_id' => 24],
            ['city' => 'Guatambú', 'state_id' => 24],
            ['city' => 'Herval d`Oeste', 'state_id' => 24],
            ['city' => 'Ibiam', 'state_id' => 24],
            ['city' => 'Ibicaré', 'state_id' => 24],
            ['city' => 'Ibirama', 'state_id' => 24],
            ['city' => 'Içara', 'state_id' => 24],
            ['city' => 'Ilhota', 'state_id' => 24],
            ['city' => 'Imaruí', 'state_id' => 24],
            ['city' => 'Imbituba', 'state_id' => 24],
            ['city' => 'Imbuia', 'state_id' => 24],
            ['city' => 'Indaial', 'state_id' => 24],
            ['city' => 'Iomerê', 'state_id' => 24],
            ['city' => 'Ipira', 'state_id' => 24],
            ['city' => 'Iporã do Oeste', 'state_id' => 24],
            ['city' => 'Ipuaçu', 'state_id' => 24],
            ['city' => 'Ipumirim', 'state_id' => 24],
            ['city' => 'Iraceminha', 'state_id' => 24],
            ['city' => 'Irani', 'state_id' => 24],
            ['city' => 'Irati', 'state_id' => 24],
            ['city' => 'Irineópolis', 'state_id' => 24],
            ['city' => 'Itá', 'state_id' => 24],
            ['city' => 'Itaiópolis', 'state_id' => 24],
            ['city' => 'Itajaí', 'state_id' => 24],
            ['city' => 'Itapema', 'state_id' => 24],
            ['city' => 'Itapiranga', 'state_id' => 24],
            ['city' => 'Itapoá', 'state_id' => 24],
            ['city' => 'Ituporanga', 'state_id' => 24],
            ['city' => 'Jaborá', 'state_id' => 24],
            ['city' => 'Jacinto Machado', 'state_id' => 24],
            ['city' => 'Jaguaruna', 'state_id' => 24],
            ['city' => 'Jaraguá do Sul', 'state_id' => 24],
            ['city' => 'Jardinópolis', 'state_id' => 24],
            ['city' => 'Joaçaba', 'state_id' => 24],
            ['city' => 'Joinville', 'state_id' => 24],
            ['city' => 'José Boiteux', 'state_id' => 24],
            ['city' => 'Jupiá', 'state_id' => 24],
            ['city' => 'Lacerdópolis', 'state_id' => 24],
            ['city' => 'Lages', 'state_id' => 24],
            ['city' => 'Laguna', 'state_id' => 24],
            ['city' => 'Lajeado Grande', 'state_id' => 24],
            ['city' => 'Laurentino', 'state_id' => 24],
            ['city' => 'Lauro Muller', 'state_id' => 24],
            ['city' => 'Lebon Régis', 'state_id' => 24],
            ['city' => 'Leoberto Leal', 'state_id' => 24],
            ['city' => 'Lindóia do Sul', 'state_id' => 24],
            ['city' => 'Lontras', 'state_id' => 24],
            ['city' => 'Luiz Alves', 'state_id' => 24],
            ['city' => 'Luzerna', 'state_id' => 24],
            ['city' => 'Macieira', 'state_id' => 24],
            ['city' => 'Mafra', 'state_id' => 24],
            ['city' => 'Major Gercino', 'state_id' => 24],
            ['city' => 'Major Vieira', 'state_id' => 24],
            ['city' => 'Maracajá', 'state_id' => 24],
            ['city' => 'Maravilha', 'state_id' => 24],
            ['city' => 'Marema', 'state_id' => 24],
            ['city' => 'Massaranduba', 'state_id' => 24],
            ['city' => 'Matos Costa', 'state_id' => 24],
            ['city' => 'Meleiro', 'state_id' => 24],
            ['city' => 'Mirim Doce', 'state_id' => 24],
            ['city' => 'Modelo', 'state_id' => 24],
            ['city' => 'Mondaí', 'state_id' => 24],
            ['city' => 'Monte Carlo', 'state_id' => 24],
            ['city' => 'Monte Castelo', 'state_id' => 24],
            ['city' => 'Morro da Fumaça', 'state_id' => 24],
            ['city' => 'Morro Grande', 'state_id' => 24],
            ['city' => 'Navegantes', 'state_id' => 24],
            ['city' => 'Nova Erechim', 'state_id' => 24],
            ['city' => 'Nova Itaberaba', 'state_id' => 24],
            ['city' => 'Nova Trento', 'state_id' => 24],
            ['city' => 'Nova Veneza', 'state_id' => 24],
            ['city' => 'Novo Horizonte', 'state_id' => 24],
            ['city' => 'Orleans', 'state_id' => 24],
            ['city' => 'Otacílio Costa', 'state_id' => 24],
            ['city' => 'Ouro', 'state_id' => 24],
            ['city' => 'Ouro Verde', 'state_id' => 24],
            ['city' => 'Paial', 'state_id' => 24],
            ['city' => 'Painel', 'state_id' => 24],
            ['city' => 'Palhoça', 'state_id' => 24],
            ['city' => 'Palma Sola', 'state_id' => 24],
            ['city' => 'Palmeira', 'state_id' => 24],
            ['city' => 'Palmitos', 'state_id' => 24],
            ['city' => 'Papanduva', 'state_id' => 24],
            ['city' => 'Paraíso', 'state_id' => 24],
            ['city' => 'Passo de Torres', 'state_id' => 24],
            ['city' => 'Passos Maia', 'state_id' => 24],
            ['city' => 'Paulo Lopes', 'state_id' => 24],
            ['city' => 'Pedras Grandes', 'state_id' => 24],
            ['city' => 'Penha', 'state_id' => 24],
            ['city' => 'Peritiba', 'state_id' => 24],
            ['city' => 'Petrolândia', 'state_id' => 24],
            ['city' => 'Piçarras', 'state_id' => 24],
            ['city' => 'Pinhalzinho', 'state_id' => 24],
            ['city' => 'Pinheiro Preto', 'state_id' => 24],
            ['city' => 'Piratuba', 'state_id' => 24],
            ['city' => 'Planalto Alegre', 'state_id' => 24],
            ['city' => 'Pomerode', 'state_id' => 24],
            ['city' => 'Ponte Alta', 'state_id' => 24],
            ['city' => 'Ponte Alta do Norte', 'state_id' => 24],
            ['city' => 'Ponte Serrada', 'state_id' => 24],
            ['city' => 'Porto Belo', 'state_id' => 24],
            ['city' => 'Porto União', 'state_id' => 24],
            ['city' => 'Pouso Redondo', 'state_id' => 24],
            ['city' => 'Praia Grande', 'state_id' => 24],
            ['city' => 'Presidente Castelo Branco', 'state_id' => 24],
            ['city' => 'Presidente Getúlio', 'state_id' => 24],
            ['city' => 'Presidente Nereu', 'state_id' => 24],
            ['city' => 'Princesa', 'state_id' => 24],
            ['city' => 'Quilombo', 'state_id' => 24],
            ['city' => 'Rancho Queimado', 'state_id' => 24],
            ['city' => 'Rio das Antas', 'state_id' => 24],
            ['city' => 'Rio do Campo', 'state_id' => 24],
            ['city' => 'Rio do Oeste', 'state_id' => 24],
            ['city' => 'Rio do Sul', 'state_id' => 24],
            ['city' => 'Rio dos Cedros', 'state_id' => 24],
            ['city' => 'Rio Fortuna', 'state_id' => 24],
            ['city' => 'Rio Negrinho', 'state_id' => 24],
            ['city' => 'Rio Rufino', 'state_id' => 24],
            ['city' => 'Riqueza', 'state_id' => 24],
            ['city' => 'Rodeio', 'state_id' => 24],
            ['city' => 'Romelândia', 'state_id' => 24],
            ['city' => 'Salete', 'state_id' => 24],
            ['city' => 'Saltinho', 'state_id' => 24],
            ['city' => 'Salto Veloso', 'state_id' => 24],
            ['city' => 'Sangão', 'state_id' => 24],
            ['city' => 'Santa Cecília', 'state_id' => 24],
            ['city' => 'Santa Helena', 'state_id' => 24],
            ['city' => 'Santa Rosa de Lima', 'state_id' => 24],
            ['city' => 'Santa Rosa do Sul', 'state_id' => 24],
            ['city' => 'Santa Terezinha', 'state_id' => 24],
            ['city' => 'Santa Terezinha do Progresso', 'state_id' => 24],
            ['city' => 'Santiago do Sul', 'state_id' => 24],
            ['city' => 'Santo Amaro da Imperatriz', 'state_id' => 24],
            ['city' => 'São Bento do Sul', 'state_id' => 24],
            ['city' => 'São Bernardino', 'state_id' => 24],
            ['city' => 'São Bonifácio', 'state_id' => 24],
            ['city' => 'São Carlos', 'state_id' => 24],
            ['city' => 'São Cristovão do Sul', 'state_id' => 24],
            ['city' => 'São Domingos', 'state_id' => 24],
            ['city' => 'São Francisco do Sul', 'state_id' => 24],
            ['city' => 'São João Batista', 'state_id' => 24],
            ['city' => 'São João do Itaperiú', 'state_id' => 24],
            ['city' => 'São João do Oeste', 'state_id' => 24],
            ['city' => 'São João do Sul', 'state_id' => 24],
            ['city' => 'São Joaquim', 'state_id' => 24],
            ['city' => 'São José', 'state_id' => 24],
            ['city' => 'São José do Cedro', 'state_id' => 24],
            ['city' => 'São José do Cerrito', 'state_id' => 24],
            ['city' => 'São Lourenço do Oeste', 'state_id' => 24],
            ['city' => 'São Ludgero', 'state_id' => 24],
            ['city' => 'São Martinho', 'state_id' => 24],
            ['city' => 'São Miguel da Boa Vista', 'state_id' => 24],
            ['city' => 'São Miguel do Oeste', 'state_id' => 24],
            ['city' => 'São Pedro de Alcântara', 'state_id' => 24],
            ['city' => 'Saudades', 'state_id' => 24],
            ['city' => 'Schroeder', 'state_id' => 24],
            ['city' => 'Seara', 'state_id' => 24],
            ['city' => 'Serra Alta', 'state_id' => 24],
            ['city' => 'Siderópolis', 'state_id' => 24],
            ['city' => 'Sombrio', 'state_id' => 24],
            ['city' => 'Sul Brasil', 'state_id' => 24],
            ['city' => 'Taió', 'state_id' => 24],
            ['city' => 'Tangará', 'state_id' => 24],
            ['city' => 'Tigrinhos', 'state_id' => 24],
            ['city' => 'Tijucas', 'state_id' => 24],
            ['city' => 'Timbé do Sul', 'state_id' => 24],
            ['city' => 'Timbó', 'state_id' => 24],
            ['city' => 'Timbó Grande', 'state_id' => 24],
            ['city' => 'Três Barras', 'state_id' => 24],
            ['city' => 'Treviso', 'state_id' => 24],
            ['city' => 'Treze de Maio', 'state_id' => 24],
            ['city' => 'Treze Tílias', 'state_id' => 24],
            ['city' => 'Trombudo Central', 'state_id' => 24],
            ['city' => 'Tubarão', 'state_id' => 24],
            ['city' => 'Tunápolis', 'state_id' => 24],
            ['city' => 'Turvo', 'state_id' => 24],
            ['city' => 'União do Oeste', 'state_id' => 24],
            ['city' => 'Urubici', 'state_id' => 24],
            ['city' => 'Urupema', 'state_id' => 24],
            ['city' => 'Urussanga', 'state_id' => 24],
            ['city' => 'Vargeão', 'state_id' => 24],
            ['city' => 'Vargem', 'state_id' => 24],
            ['city' => 'Vargem Bonita', 'state_id' => 24],
            ['city' => 'Vidal Ramos', 'state_id' => 24],
            ['city' => 'Videira', 'state_id' => 24],
            ['city' => 'Vitor Meireles', 'state_id' => 24],
            ['city' => 'Witmarsum', 'state_id' => 24],
            ['city' => 'Xanxerê', 'state_id' => 24],
            ['city' => 'Xavantina', 'state_id' => 24],
            ['city' => 'Xaxim', 'state_id' => 24],
            ['city' => 'Zortéa', 'state_id' => 24]
        ]);

        $this->command->info('Cidades de Santa Catarina importadas com sucesso!');
    }
}
