<?php

namespace Database\Seeders\Estados;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CidadesRioGrandeDoNorteSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cities')->insert([
        	['city' => 'Acari', 'state_id' => 20],
            ['city' => 'Açu', 'state_id' => 20],
            ['city' => 'Afonso Bezerra', 'state_id' => 20],
            ['city' => 'Água Nova', 'state_id' => 20],
            ['city' => 'Alexandria', 'state_id' => 20],
            ['city' => 'Almino Afonso', 'state_id' => 20],
            ['city' => 'Alto do Rodrigues', 'state_id' => 20],
            ['city' => 'Angicos', 'state_id' => 20],
            ['city' => 'Antônio Martins', 'state_id' => 20],
            ['city' => 'Apodi', 'state_id' => 20],
            ['city' => 'Areia Branca', 'state_id' => 20],
            ['city' => 'Arês', 'state_id' => 20],
            ['city' => 'Augusto Severo', 'state_id' => 20],
            ['city' => 'Baía Formosa', 'state_id' => 20],
            ['city' => 'Baraúna', 'state_id' => 20],
            ['city' => 'Barcelona', 'state_id' => 20],
            ['city' => 'Bento Fernandes', 'state_id' => 20],
            ['city' => 'Bodó', 'state_id' => 20],
            ['city' => 'Bom Jesus', 'state_id' => 20],
            ['city' => 'Brejinho', 'state_id' => 20],
            ['city' => 'Caiçara do Norte', 'state_id' => 20],
            ['city' => 'Caiçara do Rio do Vento', 'state_id' => 20],
            ['city' => 'Caicó', 'state_id' => 20],
            ['city' => 'Campo Redondo', 'state_id' => 20],
            ['city' => 'Canguaretama', 'state_id' => 20],
            ['city' => 'Caraúbas', 'state_id' => 20],
            ['city' => 'Carnaúba dos Dantas', 'state_id' => 20],
            ['city' => 'Carnaubais', 'state_id' => 20],
            ['city' => 'Ceará-Mirim', 'state_id' => 20],
            ['city' => 'Cerro Corá', 'state_id' => 20],
            ['city' => 'Coronel Ezequiel', 'state_id' => 20],
            ['city' => 'Coronel João Pessoa', 'state_id' => 20],
            ['city' => 'Cruzeta', 'state_id' => 20],
            ['city' => 'Currais Novos', 'state_id' => 20],
            ['city' => 'Doutor Severiano', 'state_id' => 20],
            ['city' => 'Encanto', 'state_id' => 20],
            ['city' => 'Equador', 'state_id' => 20],
            ['city' => 'Espírito Santo', 'state_id' => 20],
            ['city' => 'Extremoz', 'state_id' => 20],
            ['city' => 'Felipe Guerra', 'state_id' => 20],
            ['city' => 'Fernando Pedroza', 'state_id' => 20],
            ['city' => 'Florânia', 'state_id' => 20],
            ['city' => 'Francisco Dantas', 'state_id' => 20],
            ['city' => 'Frutuoso Gomes', 'state_id' => 20],
            ['city' => 'Galinhos', 'state_id' => 20],
            ['city' => 'Goianinha', 'state_id' => 20],
            ['city' => 'Governador Dix-Sept Rosado', 'state_id' => 20],
            ['city' => 'Grossos', 'state_id' => 20],
            ['city' => 'Guamaré', 'state_id' => 20],
            ['city' => 'Ielmo Marinho', 'state_id' => 20],
            ['city' => 'Ipanguaçu', 'state_id' => 20],
            ['city' => 'Ipueira', 'state_id' => 20],
            ['city' => 'Itajá', 'state_id' => 20],
            ['city' => 'Itaú', 'state_id' => 20],
            ['city' => 'Jaçanã', 'state_id' => 20],
            ['city' => 'Jandaíra', 'state_id' => 20],
            ['city' => 'Janduís', 'state_id' => 20],
            ['city' => 'Januário Cicco', 'state_id' => 20],
            ['city' => 'Japi', 'state_id' => 20],
            ['city' => 'Jardim de Angicos', 'state_id' => 20],
            ['city' => 'Jardim de Piranhas', 'state_id' => 20],
            ['city' => 'Jardim do Seridó', 'state_id' => 20],
            ['city' => 'João Câmara', 'state_id' => 20],
            ['city' => 'João Dias', 'state_id' => 20],
            ['city' => 'José da Penha', 'state_id' => 20],
            ['city' => 'Jucurutu', 'state_id' => 20],
            ['city' => 'Jundiá', 'state_id' => 20],
            ['city' => 'Lagoa d`Anta', 'state_id' => 20],
            ['city' => 'Lagoa de Pedras', 'state_id' => 20],
            ['city' => 'Lagoa de Velhos', 'state_id' => 20],
            ['city' => 'Lagoa Nova', 'state_id' => 20],
            ['city' => 'Lagoa Salgada', 'state_id' => 20],
            ['city' => 'Lajes', 'state_id' => 20],
            ['city' => 'Lajes Pintadas', 'state_id' => 20],
            ['city' => 'Lucrécia', 'state_id' => 20],
            ['city' => 'Luís Gomes', 'state_id' => 20],
            ['city' => 'Macaíba', 'state_id' => 20],
            ['city' => 'Macau', 'state_id' => 20],
            ['city' => 'Major Sales', 'state_id' => 20],
            ['city' => 'Marcelino Vieira', 'state_id' => 20],
            ['city' => 'Martins', 'state_id' => 20],
            ['city' => 'Maxaranguape', 'state_id' => 20],
            ['city' => 'Messias Targino', 'state_id' => 20],
            ['city' => 'Montanhas', 'state_id' => 20],
            ['city' => 'Monte Alegre', 'state_id' => 20],
            ['city' => 'Monte das Gameleiras', 'state_id' => 20],
            ['city' => 'Mossoró', 'state_id' => 20],
            ['city' => 'Natal', 'state_id' => 20],
            ['city' => 'Nísia Floresta', 'state_id' => 20],
            ['city' => 'Nova Cruz', 'state_id' => 20],
            ['city' => 'Olho-d`Água do Borges', 'state_id' => 20],
            ['city' => 'Ouro Branco', 'state_id' => 20],
            ['city' => 'Paraná', 'state_id' => 20],
            ['city' => 'Paraú', 'state_id' => 20],
            ['city' => 'Parazinho', 'state_id' => 20],
            ['city' => 'Parelhas', 'state_id' => 20],
            ['city' => 'Parnamirim', 'state_id' => 20],
            ['city' => 'Passa e Fica', 'state_id' => 20],
            ['city' => 'Passagem', 'state_id' => 20],
            ['city' => 'Patu', 'state_id' => 20],
            ['city' => 'Pau dos Ferros', 'state_id' => 20],
            ['city' => 'Pedra Grande', 'state_id' => 20],
            ['city' => 'Pedra Preta', 'state_id' => 20],
            ['city' => 'Pedro Avelino', 'state_id' => 20],
            ['city' => 'Pedro Velho', 'state_id' => 20],
            ['city' => 'Pendências', 'state_id' => 20],
            ['city' => 'Pilões', 'state_id' => 20],
            ['city' => 'Poço Branco', 'state_id' => 20],
            ['city' => 'Portalegre', 'state_id' => 20],
            ['city' => 'Porto do Mangue', 'state_id' => 20],
            ['city' => 'Presidente Juscelino', 'state_id' => 20],
            ['city' => 'Pureza', 'state_id' => 20],
            ['city' => 'Rafael Fernandes', 'state_id' => 20],
            ['city' => 'Rafael Godeiro', 'state_id' => 20],
            ['city' => 'Riacho da Cruz', 'state_id' => 20],
            ['city' => 'Riacho de Santana', 'state_id' => 20],
            ['city' => 'Riachuelo', 'state_id' => 20],
            ['city' => 'Rio do Fogo', 'state_id' => 20],
            ['city' => 'Rodolfo Fernandes', 'state_id' => 20],
            ['city' => 'Ruy Barbosa', 'state_id' => 20],
            ['city' => 'Santa Cruz', 'state_id' => 20],
            ['city' => 'Santa Maria', 'state_id' => 20],
            ['city' => 'Santana do Matos', 'state_id' => 20],
            ['city' => 'Santana do Seridó', 'state_id' => 20],
            ['city' => 'Santo Antônio', 'state_id' => 20],
            ['city' => 'São Bento do Norte', 'state_id' => 20],
            ['city' => 'São Bento do Trairí', 'state_id' => 20],
            ['city' => 'São Fernando', 'state_id' => 20],
            ['city' => 'São Francisco do Oeste', 'state_id' => 20],
            ['city' => 'São Gonçalo do Amarante', 'state_id' => 20],
            ['city' => 'São João do Sabugi', 'state_id' => 20],
            ['city' => 'São José de Mipibu', 'state_id' => 20],
            ['city' => 'São José do Campestre', 'state_id' => 20],
            ['city' => 'São José do Seridó', 'state_id' => 20],
            ['city' => 'São Miguel', 'state_id' => 20],
            ['city' => 'São Miguel do Gostoso', 'state_id' => 20],
            ['city' => 'São Paulo do Potengi', 'state_id' => 20],
            ['city' => 'São Pedro', 'state_id' => 20],
            ['city' => 'São Rafael', 'state_id' => 20],
            ['city' => 'São Tomé', 'state_id' => 20],
            ['city' => 'São Vicente', 'state_id' => 20],
            ['city' => 'Senador Elói de Souza', 'state_id' => 20],
            ['city' => 'Senador Georgino Avelino', 'state_id' => 20],
            ['city' => 'Serra de São Bento', 'state_id' => 20],
            ['city' => 'Serra do Mel', 'state_id' => 20],
            ['city' => 'Serra Negra do Norte', 'state_id' => 20],
            ['city' => 'Serrinha', 'state_id' => 20],
            ['city' => 'Serrinha dos Pintos', 'state_id' => 20],
            ['city' => 'Severiano Melo', 'state_id' => 20],
            ['city' => 'Sítio Novo', 'state_id' => 20],
            ['city' => 'Taboleiro Grande', 'state_id' => 20],
            ['city' => 'Taipu', 'state_id' => 20],
            ['city' => 'Tangará', 'state_id' => 20],
            ['city' => 'Tenente Ananias', 'state_id' => 20],
            ['city' => 'Tenente Laurentino Cruz', 'state_id' => 20],
            ['city' => 'Tibau', 'state_id' => 20],
            ['city' => 'Tibau do Sul', 'state_id' => 20],
            ['city' => 'Timbaúba dos Batistas', 'state_id' => 20],
            ['city' => 'Touros', 'state_id' => 20],
            ['city' => 'Triunfo Potiguar', 'state_id' => 20],
            ['city' => 'Umarizal', 'state_id' => 20],
            ['city' => 'Upanema', 'state_id' => 20],
            ['city' => 'Várzea', 'state_id' => 20],
            ['city' => 'Venha-Ver', 'state_id' => 20],
            ['city' => 'Vera Cruz', 'state_id' => 20],
            ['city' => 'Viçosa', 'state_id' => 20],
            ['city' => 'Vila Flor', 'state_id' => 20]
        ]);

        $this->command->info('Cidades do Rio Grande do Norte importadas com sucesso!');
    }
}
